apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql.cnf: |
    [mysqld]
    # Character Set
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    init-connect='SET NAMES utf8mb4'
    
    bind-address=0.0.0.0
    
    [mysql]
    default-character-set=utf8mb4
    
    [client]
    default-character-set=utf8mb4