apiVersion: v2
name: wp
description: WordPress with MySQL (Bitnami) demo
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami