apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wp.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "wp.name" . }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" | quote }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ include "wp.fullname" . }}
                port:
                  number: {{ .Values.wordpress.service.port }}